### ISSUE TITLE
MQF2DistributionLoss - RuntimeError: Expected all tensors to be on the same device

### ISSUE THREAD

**Issue by andreareds** [jdb78/pytorch-forecasting#1182]
- PyTorch-Forecasting version: 0.10.3
- PyTorch version: 1.12.1
- Python version: 3.10.6
- Operating System: 20.04.5 LTS

### Expected behaviour

I want to train a TFT model using the MQF2DistributionLoss for a set of bivariate time series.

### Actual behaviour

However, when I try to train, I get the following error. I tried to move the loss .to(torch.device('cuda')) as specified by the exception, and the model can be trained, but then I had an error in the inference step when I made the prediction.

`  
Traceback (most recent call last):
  File "/home/arossi/anaconda3/envs/tsapt/lib/python3.10/site-packages/pytorch_forecasting/metrics/base_metrics.py", line 342, in forward
    res = metric(
  File "/home/arossi/anaconda3/envs/tsapt/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/arossi/anaconda3/envs/tsapt/lib/python3.10/site-packages/torchmetrics/metric.py", line 245, in forward
    self._forward_cache = self._forward_reduce_state_update(*args, **kwargs)
  File "/home/arossi/anaconda3/envs/tsapt/lib/python3.10/site-packages/torchmetrics/metric.py", line 309, in _forward_reduce_state_update
    self.update(*args, **kwargs)
  File "/home/arossi/anaconda3/envs/tsapt/lib/python3.10/site-packages/torchmetrics/metric.py", line 395, in wrapped_func
    update(*args, **kwargs)
TypeError: MultiHorizonMetric.update() got an unexpected keyword argument 'encoder_target'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/arossi/anaconda3/envs/tsapt/lib/python3.10/site-packages/torchmetrics/metric.py", line 395, in wrapped_func
    update(*args, **kwargs)
  File "/home/arossi/anaconda3/envs/tsapt/lib/python3.10/site-packages/pytorch_forecasting/metrics/base_metrics.py", line 785, in update
    losses = self.loss(y_pred, target)
  File "/home/arossi/anaconda3/envs/tsapt/lib/python3.10/site-packages/pytorch_forecasting/metrics/distributions.py", line 368, in loss
    loss = distribution.energy_score(y_actual)
  File "/home/arossi/anaconda3/envs/tsapt/lib/python3.10/site-packages/pytorch_forecasting/metrics/_mqf2_utils.py", line 501, in energy_score
    loss = self.base_dist.energy_score(z)
  File "/home/arossi/anaconda3/envs/tsapt/lib/python3.10/site-packages/pytorch_forecasting/metrics/_mqf2_utils.py", line 366, in energy_score
    loss = self.picnn.energy_score(z, reshaped_hidden_state, es_num_samples=es_num_samples, beta=beta)
  File "/home/arossi/anaconda3/envs/tsapt/lib/python3.10/site-packages/pytorch_forecasting/metrics/_mqf2_utils.py", line 184, in energy_score
    w = self.es_sample(hidden_state_repeat, dimension)
File "/home/arossi/anaconda3/envs/tsapt/lib/python3.10/site-packages/pytorch_forecasting/metrics/_mqf2_utils.py", line 137, in es_sample
    samples = self.forward(
  File "/home/arossi/anaconda3/envs/tsapt/lib/python3.10/site-packages/pytorch_forecasting/metrics/_mqf2_utils.py", line 109, in forward
    x = network.forward(x, context=context)
  File "/home/arossi/anaconda3/envs/tsapt/lib/python3.10/site-packages/cpflows/flows/cpflows.py", line 108, in forward
    F = self.get_potential(x, context)
  File "/home/arossi/anaconda3/envs/tsapt/lib/python3.10/site-packages/pytorch_forecasting/metrics/_mqf2_utils.py", line 70, in get_potential
    output = self.picnn(x, context)
  File "/home/arossi/anaconda3/envs/tsapt/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/arossi/anaconda3/envs/tsapt/lib/python3.10/site-packages/cpflows/icnn.py", line 698, in forward
    z = symm_softplus(self.actnorm0(self.Wzs[0](x)), self.act)
  File "/home/arossi/anaconda3/envs/tsapt/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/arossi/anaconda3/envs/tsapt/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat1 in method wrapper_addmm)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/arossi/tsa_crt/tft_training.py", line 63, in <module>
    model.fit()
  File "/home/arossi/tsa_crt/models/dl/tft.py", line 83, in fit
    self.trainer.fit(
  File "/home/arossi/anaconda3/envs/tsapt/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
  File "/home/arossi/anaconda3/envs/tsapt/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/arossi/anaconda3/envs/tsapt/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 735, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/arossi/anaconda3/envs/tsapt/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1166, in _run
    results = self._run_stage()
  File "/home/arossi/anaconda3/envs/tsapt/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1252, in _run_stage    
return self._run_train()
  File "/home/arossi/anaconda3/envs/tsapt/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1274, in _run_train
    self._run_sanity_check()
  File "/home/arossi/anaconda3/envs/tsapt/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1343, in _run_sanity_check
    val_loop.run()
  File "/home/arossi/anaconda3/envs/tsapt/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/home/arossi/anaconda3/envs/tsapt/lib/python3.10/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 155, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/home/arossi/anaconda3/envs/tsapt/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/home/arossi/anaconda3/envs/tsapt/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 143, in advance
    output = self._evaluation_step(**kwargs)
  File "/home/arossi/anaconda3/envs/tsapt/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 240, in _evaluation_step
    output = self.trainer._call_strategy_hook(hook_name, *kwargs.values())
  File "/home/arossi/anaconda3/envs/tsapt/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1704, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/arossi/anaconda3/envs/tsapt/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 370, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "/home/arossi/anaconda3/envs/tsapt/lib/python3.10/site-packages/pytorch_forecasting/models/base_model.py", line 419, in validation_step
    log, out = self.step(x, y, batch_idx)
  File "/home/arossi/anaconda3/envs/tsapt/lib/python3.10/site-packages/pytorch_forecasting/models/base_model.py", line 565, in step
    loss = self.loss(prediction, y, **mase_kwargs)
  File "/home/arossi/anaconda3/envs/tsapt/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/arossi/anaconda3/envs/tsapt/lib/python3.10/site-packages/pytorch_forecasting/metrics/base_metrics.py", line 351, in forward
    res = metric(y_pred[idx], (y_actual[0][idx], y_actual[1]))
  File "/home/arossi/anaconda3/envs/tsapt/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/arossi/anaconda3/envs/tsapt/lib/python3.10/site-packages/torchmetrics/metric.py", line 245, in forward
    self._forward_cache = self._forward_reduce_state_update(*args, **kwargs)
  File "/home/arossi/anaconda3/envs/tsapt/lib/python3.10/site-packages/torchmetrics/metric.py", line 309, in _forward_reduce_state_update
    self.update(*args, **kwargs)
  File "/home/arossi/anaconda3/envs/tsapt/lib/python3.10/site-packages/torchmetrics/metric.py", line 398, in wrapped_func
    raise RuntimeError(
RuntimeError: Encountered different devices in metric calculation (see stacktrace for details). This could be due to the metric class not being on the same device as input. Instead of `metric=MQF2DistributionLoss(...)` try to do `metric=MQF2DistributionLoss(...).to(device)` where device corresponds to the device of the input.`

### Code to reproduce the problem

```
    def create_model(self):
        """
        Create an instance of the model. This function contains the definition and the library of the model
        :return: None
        """
        # configure network and trainer
        early_stop_callback = EarlyStopping(monitor="val_loss", min_delta=1e-4, patience=50, verbose=False, mode="min")
        lr_logger = LearningRateMonitor()  # log the learning rate
        logger = TensorBoardLogger(self.talos_path)  # logging results to a tensorboard
        checkpoint_callback = ModelCheckpoint(monitor='val_loss',
                                              dirpath=self.talos_path,
                                              filename=self.name + '-{epoch:02d}-{val_loss:.2f}')

        self.trainer = pl.Trainer(
            max_epochs=self.p['epochs'],
            accelerator="auto",
            enable_model_summary=True,
            gradient_clip_val=self.p['gradient_clip_val'],
            limit_train_batches=30,
            callbacks=[lr_logger, early_stop_callback, checkpoint_callback],
            logger=logger,
            default_root_dir=self.talos_path
        )

        if len(self.ds.target_name) == 1:
            self.model = TemporalFusionTransformer.from_dataset(
                self.ds.X_train,
                learning_rate=self.p['lr'],
                hidden_size=self.p['hidden_size'],
                attention_head_size=self.p['attention_head_size'],
                dropout=self.p['dropout'],
                hidden_continuous_size=self.p['hidden_continuous_size'],
                output_size=7,  # 7 quantiles by default
                loss=QuantileLoss(),
                reduce_on_plateau_patience=4,
            )
        else:
            loss = MQF2DistributionLoss(prediction_length=self.ds.output_window + self.ds.horizon)
            loss.requires_grad = True

            self.model = TemporalFusionTransformer.from_dataset(
                self.ds.X_train,
                learning_rate=self.p['lr'],
                hidden_size=self.p['hidden_size'],
                attention_head_size=self.p['attention_head_size'],
                dropout=self.p['dropout'],
                hidden_continuous_size=self.p['hidden_continuous_size'],
                loss=loss,  # .to(torch.device('cuda')),
                reduce_on_plateau_patience=4,
            )
```

Thanks for your time.

**Comment by andreareds** [comment]
To add more details on this. On the CPU, it works perfectly. I also tried with other DistributionLoss, and there are not issues. So I guess there is some tensor instantiated by the MQF2 function that messes up everything.

**Comment by jonkiszp** [comment]
I have this same problem if TimeSeriesDataSet is multi target else target is single everything is ok

**Comment by mvrozanti** [comment]
I'm also having this problem even when TimeSeriesDataSet is single target

**Comment by fkiraly** [comment]
@andreareds, @jonkiszp, @mvrozanti, can you please add *fully reproducible code* for this bug?

This should include:

* generation or loading of data, optimally using dummy data generated in-code
* all imports of relevant objects

Without the above, we will be unable to reproduce or diagnose the issue - thanks a lot for your help.

**Comment by mvrozanti** [comment]
```
import torch
import pandas as pd
import numpy as np

from pytorch_forecasting import TimeSeriesDataSet, TemporalFusionTransformer
from pytorch_forecasting.data import NaNLabelEncoder
from pytorch_lightning import Trainer, LightningModule

rows = 15
df = pd.DataFrame({
    "time": pd.date_range("2020-01-01", periods=rows, freq="h"),
    "label": ["test"] * rows,
    "var1": np.random.randn(rows).cumsum(),
    "var2": np.random.randn(rows).cumsum(),
})
df = df.sort_values("time").reset_index(drop=True)
df["past_var1"] = df["var1"].shift(-1)
df.dropna(subset=["past_var1"], inplace=True)
df["time_idx"] = range(len(df))

dataset = TimeSeriesDataSet(
    df,
    time_idx="time_idx",
    target="past_var1",
    group_ids=["label"],
    static_categoricals=["label"],
    time_varying_known_reals=["var1", "var2"],
    time_varying_unknown_reals=["past_var1"],
    max_encoder_length=5,
    max_prediction_length=2,
    categorical_encoders={"label": NaNLabelEncoder(add_nan=False)},
)

class PatchedTFT(TemporalFusionTransformer):
    def forward(self, x, *args, **kwargs):
        device = next(self.parameters()).device
        for key, value in x.items():
            x[key] = value.to(device)
        return super().forward(x, *args, **kwargs)

class TFTModule(LightningModule):
    def __init__(self, tft):
        super().__init__()
        self.tft = tft

    def forward(self, x):
        return self.tft(x)

    def training_step(self, batch, batch_idx):
        x, y = batch
        y = y[0]
        y_hat = self(x)
        y_hat = y_hat.prediction
        loss = self.tft.loss(y_hat, y)
        self.log("train_loss", loss)
        return loss

    def configure_optimizers(self):
        return torch.optim.Adam(self.parameters(), lr=1e-3)

model_tft = PatchedTFT.from_dataset(dataset)
model = TFTModule(model_tft)

trainer = Trainer(
    accelerator="gpu",  # 'cpu' works fine
    devices=1,
    max_epochs=2,
    detect_anomaly=True,
    limit_train_batches=1
)

dataloader = dataset.to_dataloader(train=True, batch_size=4, num_workers=0)
trainer.fit(model, dataloader)
```

Am I using it correctly? This same script fails when the accelerator is gpu, but not cpu.

**Comment by benHeid** [comment]
The reason is that your model is not completely on the GPU. 

replace `model_tft = PatchedTFT.from_dataset(dataset)` with `model_tft = TemporalFusionTransformer.from_dataset(dataset).to("gpu")` should work. Can you confirm if this works? 

@fkiraly do we need an improvement of the documentation here?

**Comment by mvrozanti** [comment]
Oops :smile: works fine for me now. Thanks!

**Comment by benHeid** [comment]
So can we close this issue. Or is something else still open?

**Comment by cngmid** [comment]
Actually the original question was about `MQF2DistributionLoss`, which is not used in the example above.

The code

```python
from lightning import LightningModule
import torch
import pandas as pd
import numpy as np
import lightning.pytorch as pl

from pytorch_forecasting import TimeSeriesDataSet, TemporalFusionTransformer
from pytorch_forecasting.data import NaNLabelEncoder
from pytorch_forecasting.models.temporal_fusion_transformer import TemporalFusionTransformer
from pytorch_forecasting.metrics import MQF2DistributionLoss, QuantileLoss

rows = 15
df = pd.DataFrame({
    "time": pd.date_range("2025-01-01", periods=rows, freq="h"),
    "label": ["test"] * rows,
    "var1": np.random.randn(rows).cumsum(),
    "var2": np.random.randn(rows).cumsum(),
})
df = df.sort_values("time").reset_index(drop=True)
df["past_var1"] = df["var1"].shift(-1)
df.dropna(subset=["past_var1"], inplace=True)
df["time_idx"] = range(len(df))

dataset = TimeSeriesDataSet(
    df,
    time_idx="time_idx",
    target="past_var1",
    group_ids=["label"],
    static_categoricals=["label"],
    time_varying_known_reals=["var1", "var2"],
    time_varying_unknown_reals=["past_var1"],
    max_encoder_length=5,
    max_prediction_length=2,
    categorical_encoders={"label": NaNLabelEncoder(add_nan=False)},
)

# model_tft = TemporalFusionTransformer.from_dataset(dataset, loss=QuantileLoss())
model_tft = TemporalFusionTransformer.from_dataset(dataset, loss=MQF2DistributionLoss(prediction_length=2))

trainer = pl.Trainer(
    max_epochs=10,
    accelerator="gpu",
    devices="auto",
    gradient_clip_val=0.1,
    limit_train_batches=30,
    limit_val_batches=3,
    # fast_dev_run=True,
    # logger=logger,
    # profiler=True,
    #callbacks=[lr_logger, early_stop_callback],
)

dataloader = dataset.to_dataloader(train=True, batch_size=4, num_workers=0)
trainer.fit(model_tft, dataloader)

raw_predictions = model_tft.predict(dataloader, mode="raw", return_x=True, trainer_kwargs=dict(accelerator='cuda'))
model_tft.plot_prediction(raw_predictions.x, raw_predictions.output, idx=0)
```

throws the error:
```
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat1 in method wrapper_CUDA_addmm)
```

The error doesn't appear with `accelerator='cuda'`. 
Using the loss `QuantileLoss` would work both with `cuda` and `cpu`.

**Comment by fnhirwa** [comment]
This is indeed a bug, it seems like the `MQF2DistributionLoss` class `picnn` isn't being moved to the same device as input tensors (it is being initialized on CPU during loss class construction)

I will open a PR to fix this issue.
