### ISSUE TITLE
TFT prediction at inference time for unseen entity key fails

### ISSUE THREAD

**Issue by andre-marcos-perez** [jdb78/pytorch-forecasting#1345]
- PyTorch-Forecasting version: 1.0.0
- PyTorch version: 2.0.0
- Python version: 3.10
- Operating System: Mac OS 13.1v

### Expected behaviour

I get predictions at inference time on unseen entity key (set in the `TimeSeriesDataSet`  `group_ids` param at training time).

### Actual behaviour

I get an error saying that the entity key is an unknown category.

### Code to reproduce the problem

Hi, I am struggling to understand how to get predictions at inference time when the entity keys (set in the `TimeSeriesDataSet`  `group_ids` param at training time) are not present in the training or validation time series datasets. The following pseudo-code:

```python
# -- training
training_ts_dataset: TimeSeriesDataSet = TimeSeriesDataSet(...)
params = training_ts_dataset.get_parameters()

# -- inference
inference_df: pd.DataFrame(...) # single entity df with schema (unseen entity key + time index + features)
inference_ts_dataset = TimeSeriesDataSet.from_parameters(data= inference_df, parameters=params, predict=True)
predictions = model.predict(inference_ts_dataset.to_dataloader(train=False), raw=True)
```

Throws this error stating that the unseen entity key is an unknown category (except it is a group id).

```python
"Unknown category '<unseen-entity-key>' encountered. Set `add_nan=True` to allow unknown categories"
Traceback (most recent call last):
  File ".../pytorch_forecasting/data/encoders.py", line 331, in transform
    encoded = [self.classes_[v] for v in y]
  File ".../pytorch_forecasting/data/encoders.py", line 331, in <listcomp>
    encoded = [self.classes_[v] for v in y]
KeyError: '<unseen-entity-key>'
```

**Comment by andre-marcos-perez** [comment]
Which is the best approach to make predictions at inference time as stateless as possible? I am having to carry not only the model but also the training dataset to the inference system just because I have to load the model from `TimeSeriesDataSet`.

**Comment by andre-marcos-perez** [comment]
I am wondering if I have to build the `TimeSeriesDataSet` using both `training` and `inference` data, I will never be able to make this model run prediction in `live` mode, right?

**Comment by andre-marcos-perez** [comment]
Some updates, I noticed that the `TimeSeriesDataSet` adds the `group_ids` columns on the `categorical_encoders` [here](https://github.com/jdb78/pytorch-forecasting/blob/7c775c1a2fe3effe62eac0a476db98ca5b24ca4c/pytorch_forecasting/data/timeseries.py#L696). It happens inside the `_preprocess_data` method that is called when the object is created. This seems to be the source of the problem since the groups are learned at `training` time and newer groups at `inference` time won't go through. This effectively explains the error since the default encoder appended to the group ids columns is sklearn's [LabelEncoder](https://github.com/jdb78/pytorch-forecasting/blob/7c775c1a2fe3effe62eac0a476db98ca5b24ca4c/pytorch_forecasting/data/timeseries.py#L305).

```python
KeyError: "Unknown category '<unseen-entity-key>' encountered. Set `add_nan=True` to allow unknown categories"
```

**Comment by andre-marcos-perez** [comment]
I actually found a workaround that decouples training and inference, wdyt?

At `training` time:

- Create a `TimeSeriesDataSet` with training data;
- Save the serialised `TimeSeriesDataSet` parameters.

```python
training_ts_dataset: TimeSeriesDataSet = TimeSeriesDataSet(data=training_df, ...)
training_params: dict = training_ts_dataset.get_parameters()
joblib.dump(training_params, "params.joblib"))
```

At inference time:

- Create a `TimeSeriesDataSet` with inference data;
- Load the training `TimeSeriesDataSet` serialised parameters;
- Replace the group id cols encoders in the training parameters with the inference ones;
- Create a `TimeSeriesDataSet` with inference data and the training params.

```python
# inference stuff
inference_ts_dataset: TimeSeriesDataSet = TimeSeriesDataSet(data=inference_df, ...)
inference_params: dict = inference_ts_dataset.get_parameters()

# training stuff
training_params: dict = joblib.load("params.joblib")
training_params["categorical_encoders"]["__group_id__<entity-key>"] = inference_params["categorical_encoders"]["__group_id__<entity-key>"]
training_params["categorical_encoders"]["<entity-key>"] = inference_params["categorical_encoders"]["<entity-key>"]

# load the inference time series dataset
time_series_dataset = TimeSeriesDataSet.from_parameters(
    data= inference_df, 
    parameters= training_params,
    predict=True
)

```

**Comment by andre-marcos-perez** [comment]
Ok, I found the root cause. The quoted comment only happens when we set a `GroupNormalizer` to the `TimeSeriesDataSet.target_normalizer` param.

> Some updates, I noticed that the `TimeSeriesDataSet` adds the `group_ids` columns on the `categorical_encoders` [here](https://github.com/jdb78/pytorch-forecasting/blob/7c775c1a2fe3effe62eac0a476db98ca5b24ca4c/pytorch_forecasting/data/timeseries.py#L696). It happens inside the `_preprocess_data` method that is called when the object is created. This seems to be the source of the problem since the groups are learned at `training` time and newer groups at `inference` time won't go through. This effectively explains the error since the default encoder appended to the group ids columns is sklearn's [LabelEncoder](https://github.com/jdb78/pytorch-forecasting/blob/7c775c1a2fe3effe62eac0a476db98ca5b24ca4c/pytorch_forecasting/data/timeseries.py#L305).
> 
> ```python
> KeyError: "Unknown category '<unseen-entity-key>' encountered. Set `add_nan=True` to allow unknown categories"
> ```

I can think of two solutions to decouple training and inference in this context, both require target data to be normalised elsewhere:

- Set `TimeSeriesDataSet.target_normalizer` param to `None`. This approach might require training and inference target data to be normalised elsewhere. You can always drop target normalisation altogether.

```python
# training stuff
training_ts_dataset: TimeSeriesDataSet = TimeSeriesDataSet(
    data=training_df, # target normalised elsewhere
    ...
    target_normalizer=None,
    ...
)

# inference stuff
inference_ts_dataset = TimeSeriesDataSet.from_parameters(
    data=inference_df, # target normalised elsewhere
    parameters=training_ts_dataset.get_parameters(),
    predict=True
)
```

- Keep the `TimeSeriesDataSet.target_normalizer`, explicitly add the group id columns to the `categorical_encoders` but allow unknown categories. This approach requires inference target data to be normalised elsewhere.

```python
# training stuff
training_ts_dataset: TimeSeriesDataSet = TimeSeriesDataSet(
    ...
    target_normalizer=GroupNormalizer(groups=[<entity-key>], transformation="softplus"),
    ...
    categorical_encoders={'<entity-key>': NaNLabelEncoder(add_nan=True)},
    ...
)

# inference stuff
inference_ts_dataset = TimeSeriesDataSet.from_parameters(
    data=inference_df, # target normalised elsewhere
    parameters=training_ts_dataset.get_parameters(),
    predict=True
)
```

**Comment by abudis** [comment]
Actually in our experiments GroupNormalizer tends to perform better than the EncoderNormalizer. Unfortunately, this means that we cannot do inference for the unseen groups.

One thing to consider though is that in the linked issue it seems that the GroupNormalizer introduces leakage, which probably means that the evaluation produces an optimistic result for the GroupNormalizer.

**Comment by Gil-Frenkel** [comment]
Hi, did we have any conclusions on this?
I understand that GroupNormalizer is used by default?

In my case I do want to make inference on unseen groups (users in my case).

How should I use the EncoderNormalizer then?

Thanks!
