### ISSUE TITLE
Issue with TFT generating empty features in torch/nn/modules/linear.py

### ISSUE THREAD

**Issue by Loggy48** [jdb78/pytorch-forecasting#1354]
- PyTorch-Forecasting version: 1.0.0
- PyTorch version: 2.0.1+cu117
- Python version: 3.8.10
- Operating System: Ubuntu 20.04.6 LTS

### Expected behavior

Code would build a working TFT model from TimeSeriesDataSet data.

### Actual behavior

The code reported an error and crashed:

### Code to reproduce the problem
This stripped down code produces the error reliably either for a single target (no parameter) or for 2 targets (any parameter):

`import os
import sys
import logging
import pandas as pd
import numpy as np
import torch
import pytorch_lightning as pl
import pytorch_forecasting as pf
from pytorch_lightning import Trainer
from pytorch_lightning.callbacks import EarlyStopping,LearningRateMonitor
from pytorch_lightning.loggers import TensorBoardLogger
from pytorch_forecasting import Baseline,TimeSeriesDataSet
from pytorch_forecasting.models import TemporalFusionTransformer as TFT
from pytorch_forecasting.data import MultiNormalizer,TorchNormalizer
print("python version",sys.version)
print("pandas version",pd.__version__)
print("numpy version",np.__version__)
print("torch version",torch.__version__)
print("pytorch_forecasting version",pf.__version__)
print("pytorch_lightning version",pl.__version__)
os.environ["CUDA_VISIBLE_DEVICES"] = ""
logging.getLogger("pytorch_lightning").setLevel(logging.WARNING)
Train=pd.read_csv("ShortTrain2.csv")
Train[Train.select_dtypes(include=['float64']).columns] = Train[Train.select_dtypes(include=['float64']).columns].astype('float32')
print(Train.dtypes)
predictors=1
if len(sys.argv) > 1 :
	predictors = 2
xtarget,xtarget_normalizer,xtime_varying_known_reals,xtime_varying_unkown_reals=None,None,None,None
if predictors == 1:
	print("Using a single predictor v1_R")
# single predictor
	xtarget=['v1_R']
	xtarget_normalizer=MultiNormalizer([TorchNormalizer()])
	xtime_varying_known_reals=['v1_Act']
	xtime_varying_unknown_reals=['v1_C','v1_D','v1_V','v1_S','v1_H','v1_L','v1_R_lag10','v1_R_lag20']
else:
	print("Using 2 predictors v1_R and v2_R")
# 2 predictors
	xtarget=['v1_R','v2_R']
	xtarget_normalizer=MultiNormalizer([TorchNormalizer(),TorchNormalizer()])
	xtime_varying_known_reals=['v1_Act','v2_Act']
	xtime_varying_unknown_reals=['v1_C','v1_D','v1_V','v1_S','v1_H','v1_L','v1_R_lag10','v1_R_lag20','v2_C','v2_D','v2_V','v2_S','v2_H','v2_L','v2_R_lag10','v2_R_lag20']

print(xtarget)
print(xtarget_normalizer)
print(xtime_varying_known_reals)
print(xtime_varying_unknown_reals)
training = TimeSeriesDataSet(
	data=Train,
	add_encoder_length=True,
	add_relative_time_idx=True,
	add_target_scales=True,
	allow_missing_timesteps=True,
	group_ids=['Group'],
	max_encoder_length=10,
	max_prediction_length=20,
	min_encoder_length=5,
	min_prediction_length=1,
#	time_idx='unique',
	time_idx='time_idx',
	static_categoricals=[], # Categorical features that do not change over time - list
	static_reals=[], # Continuous features that do not change over time - list
	time_varying_known_categoricals=[], # Known in the future - list
	time_varying_unknown_categoricals=[],
	target=xtarget,
	target_normalizer=xtarget_normalizer,
	time_varying_known_reals=xtime_varying_known_reals,
	time_varying_unknown_reals=xtime_varying_unknown_reals
)
validation = TimeSeriesDataSet.from_dataset(training, Train, predict=False, stop_randomization=True)
print("Passed validation")
train_dataloader = training.to_dataloader(train=True, batch_size=16, num_workers=32,shuffle=False)
print("Created dataloaders - show first batch")
#warnings.filterwarnings("ignore")
print("Start train_dataloader comparison with baseline")
device = torch.device("cpu")
print("actuals calculated")
Baseline().to(device)
baseline_predictions = Baseline().predict(train_dataloader)
baseline_predictions = torch.cat([b.clone().detach() for b in baseline_predictions])
print("baseline_predictions calculated")
val_loss=1e6
early_stop_callback = EarlyStopping(monitor="val_loss", min_delta=1e-4, patience=10, verbose=False, mode="min")
lr_logger = LearningRateMonitor()  # log the learning rate
logger = TensorBoardLogger("lightning_logs")  # logging results to a tensorboard
trainer = Trainer(
	callbacks=[lr_logger, early_stop_callback],
	enable_model_summary=True,
	gradient_clip_val=0.1,
	limit_train_batches=10,  # comment in for training, running valiation every 30 batches
	logger=logger
)
model = TFT(
	training,
	attention_head_size=1,
	dropout=0.1,
	hidden_continuous_size=8,
	learning_rate=0.03, # 1
	log_interval=10,
	lstm_layers=1, # could be interesting
	output_size=1, # number of predictors
	reduce_on_plateau_patience=4,
)
print(f"\nNumber of parameters in network: {model.size()/1e3:.1f}k\n")
`
Paste the command(s) you ran and the output. Including a link to a colab notebook will speed up issue resolution.

python3 filename.py (no parameter prepares and tries to build a univariate model, any parameter -> 2 variate mode:

[ShortTrain2.txt](https://github.com/jdb78/pytorch-forecasting/files/12270065/ShortTrain2.txt)

If there was a crash, please include the traceback here.

Traceback (most recent call last):
  File "ShortTrain2.py", line 94, in <module>
    model = TFT(
  File "/home/jl/.local/lib/python3.8/site-packages/pytorch_forecasting/models/temporal_fusion_transformer/__init__.py", line 248, in __init__
    self.static_context_variable_selection = GatedResidualNetwork(
  File "/home/jl/.local/lib/python3.8/site-packages/pytorch_forecasting/models/temporal_fusion_transformer/sub_modules.py", line 204, in __init__
    self.fc1 = nn.Linear(self.input_size, self.hidden_size)
  File "/home/jl/.local/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 97, in __init__
    self.weight = Parameter(torch.empty((out_features, in_features), **factory_kwargs))
TypeError: empty() received an invalid combination of arguments - got (tuple, dtype=NoneType, device=NoneType), but expected one of:
 * (tuple of ints size, *, tuple of names names, torch.memory_format memory_format, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, torch.memory_format memory_format, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)

The code used to initialize the TimeSeriesDataSet and model should be also included.

TSDS preparation is Included in the code which just reads a short example from file called ShortTrain2.csv (640 lines long):

[ShortTrain2.csv](https://github.com/jdb78/pytorch-forecasting/files/12230525/ShortTrain2.csv)

**Comment by Loggy48** [comment]
I've updated this but I can't drop a .py file in - I have to copy/paste it.  The bold type lines are just comments.

**Comment by Loggy48** [comment]
Solved this.  The problem was that I omitted the .from_dataset method in the TFT.  So the line should have read:

model = TFT.from_dataset(

etc.

It's always obvious when you see it.

Sorry for the bad layout - the orginial is fine or it wouldn't run!
