### ISSUE TITLE
Issue with installation

### ISSUE THREAD

**Issue by Wiilly-B** [jdb78/pytorch-forecasting#1560]
- PyTorch-Forecasting version: 1.0.0
- PyTorch version:  2.3.0+cpu
- Python version: 3.10
- Operating System:

### Expected behavior

I executed code `pip install pytorch-forecasting`  to install pytorch forecasting and expected to get result of being able to use pytorch forecasting 

### Actual behavior

I receive an error when pip installing 

However, the result was  
```Cython.Compiler.Errors.CompileError: sklearn\ensemble\_hist_gradient_boosting\splitting.pyx
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

Traceback (most recent call last):
        File "C:\user\Cython\Build\Dependencies.py", line 1345, in cythonize_one_helper
          return cythonize_one(*m)
                 ^^^^^^^^^^^^^^^^^
        File "C:\user\Cython\Build\Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: sklearn\svm\_liblinear.pyx

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          if error_msg:
              # for SVR: epsilon is called p in libsvm
              error_repl = error_msg.decode('utf-8').replace("p < 0", "epsilon < 0")
              raise ValueError(error_repl)
          cdef BlasFunctions blas_functions
          blas_functions.dot = _dot[double]
                                   ^

```

### Code to reproduce the problem

```
pip install pytorch-forecasting
```

Paste the command(s) you ran and the output. Including a link to a colab notebook will speed up issue resolution.
If there was a crash, please include the traceback here.
The code used to initialize the TimeSeriesDataSet and model should be also included.

**Comment by ivanightingale** [comment]
`Cython.Compiler.Errors.CompileError: sklearn\svm\_liblinear.pyx`

Looks like a problem with installation of [sklearn](https://github.com/scikit-learn/scikit-learn) actually.

**Comment by sixten-mag** [comment]
I downgraded to python 3.10 and it stopped complaining.
