### ISSUE TITLE
TimeSeriesDataset documentation for `scalers` setup for `None` case

### ISSUE THREAD

**Issue by ikulyatin** [jdb78/pytorch-forecasting#204]
- PyTorch-Forecasting version: 0.7.1
- PyTorch version:  1.7.1+cu101
- Python version: 3.8.6
- Operating System: Ubuntu Pop!_OS 20.10

### Expected behavior

Executed code:
```
import numpy as np
import pandas as pd
import pprint

from pytorch_forecasting import TimeSeriesDataSet

test_data = pd.DataFrame(
    dict(
        value=np.random.rand(30) - 0.5,
        group=np.repeat(np.arange(3), 10),
        time_idx=np.tile(np.arange(10), 3),
    )
)

test_data

dataset = TimeSeriesDataSet(
    test_data,
    group_ids=["group"],
    target="value",
    time_idx="time_idx",
    min_encoder_length=5,
    max_encoder_length=5,
    min_prediction_length=2,
    max_prediction_length=2,
    scalers=None,
    target_normalizer=None,
    time_varying_unknown_reals=["value"],
)
```
 Expected a dataset object.

### Actual behavior

Got:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[...] /.venv/lib/python3.8/site-packages/pytorch_forecasting/data/timeseries.py", line 271, in __init__
    self.scalers = {} if len(scalers) == 0 else scalers
TypeError: object of type 'NoneType' has no len()
```
### Code to reproduce the problem
See above. The fix is either in the documentation (specify to set scalers to '', rather than None), or in the timeseries.py module.

**Comment by ikulyatin** [comment]
Another alternative solution: clarify in the documentation that the dictionary has to contain the name of the variable, e.g. `scalers = {"value": None}`

**Comment by jdb78** [comment]
I think the minmax scaler is not implemented at the moment - it should be easy to change that though! Also, currently, one cannot use a different scaler for inputting targets and outputting them. Might be worth adjusting this.

**Comment by jdb78** [comment]
There is now an improved check in place #220.
