### ISSUE TITLE
Error during  pip install pytorch-forecasting  ， why?

### ISSUE THREAD

**Issue by 2017wxyzwxyz** [jdb78/pytorch-forecasting#267]
- PyTorch-Forecasting version:                ?
- PyTorch version:                                    1.6.0+cpu
- Python version:                                     Python 3.8.3
- Operating System:                                 win10 Enterprise Edition LTSC  1809

Error:

(forecasting) C:\Users\wxy>pip install pytorch-forecasting
Collecting pytorch-forecasting
  Downloading pytorch_forecasting-0.8.2-py3-none-any.whl (96 kB)
     |████████████████████████████████| 96 kB 1.3 kB/s
Collecting fsspec<0.9.0,>=0.8.5
  Downloading fsspec-0.8.5-py3-none-any.whl (98 kB)
     |██████████                      | 30 kB 1.2 kB/s eta 0:00:57ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\wxy\anaconda3\envs\forecasting\lib\site-packages\pip\_vendor\urllib3\response.py", line 438, in _error_catcher
    yield
  File "C:\Users\wxy\anaconda3\envs\forecasting\lib\site-packages\pip\_vendor\urllib3\response.py", line 519, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "C:\Users\wxy\anaconda3\envs\forecasting\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 62, in read
    data = self.__fp.read(amt)
  File "C:\Users\wxy\anaconda3\envs\forecasting\lib\http\client.py", line 458, in read
    n = self.readinto(b)
  File "C:\Users\wxy\anaconda3\envs\forecasting\lib\http\client.py", line 502, in readinto
    n = self.fp.readinto(b)
  File "C:\Users\wxy\anaconda3\envs\forecasting\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\wxy\anaconda3\envs\forecasting\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\wxy\anaconda3\envs\forecasting\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\wxy\anaconda3\envs\forecasting\lib\site-packages\pip\_internal\cli\base_command.py", line 224, in _main
    status = self.run(options, args)
  File "C:\Users\wxy\anaconda3\envs\forecasting\lib\site-packages\pip\_internal\cli\req_command.py", line 180, in wrapper
    return func(self, options, args)
  File "C:\Users\wxy\anaconda3\envs\forecasting\lib\site-packages\pip\_internal\commands\install.py", line 320, in run
    requirement_set = resolver.resolve(
  File "C:\Users\wxy\anaconda3\envs\forecasting\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 121, in resolve
    self._result = resolver.resolve(
  File "C:\Users\wxy\anaconda3\envs\forecasting\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 445, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\Users\wxy\anaconda3\envs\forecasting\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 339, in resolve
    failure_causes = self._attempt_to_pin_criterion(name, criterion)
  File "C:\Users\wxy\anaconda3\envs\forecasting\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 207, in _attempt_to_pin_criterion
    criteria = self._get_criteria_to_update(candidate)
  File "C:\Users\wxy\anaconda3\envs\forecasting\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 198, in _get_criteria_to_update
    for r in self._p.get_dependencies(candidate):
  File "C:\Users\wxy\anaconda3\envs\forecasting\lib\site-packages\pip\_internal\resolution\resolvelib\provider.py", line 170, in get_dependencies
    return [
  File "C:\Users\wxy\anaconda3\envs\forecasting\lib\site-packages\pip\_internal\resolution\resolvelib\provider.py", line 170, in <listcomp>
    return [
  File "C:\Users\wxy\anaconda3\envs\forecasting\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 257, in iter_dependencies
    requires = self.dist.requires() if with_requires else ()
  File "C:\Users\wxy\anaconda3\envs\forecasting\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 239, in dist
    self._prepare()
  File "C:\Users\wxy\anaconda3\envs\forecasting\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 226, in _prepare
    dist = self._prepare_distribution()
  File "C:\Users\wxy\anaconda3\envs\forecasting\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 318, in _prepare_distribution
    return self._factory.preparer.prepare_linked_requirement(
  File "C:\Users\wxy\anaconda3\envs\forecasting\lib\site-packages\pip\_internal\operations\prepare.py", line 480, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "C:\Users\wxy\anaconda3\envs\forecasting\lib\site-packages\pip\_internal\operations\prepare.py", line 503, in _prepare_linked_requirement
    local_file = unpack_url(
  File "C:\Users\wxy\anaconda3\envs\forecasting\lib\site-packages\pip\_internal\operations\prepare.py", line 253, in unpack_url
    file = get_http_url(
  File "C:\Users\wxy\anaconda3\envs\forecasting\lib\site-packages\pip\_internal\operations\prepare.py", line 130, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "C:\Users\wxy\anaconda3\envs\forecasting\lib\site-packages\pip\_internal\network\download.py", line 163, in __call__
    for chunk in chunks:
  File "C:\Users\wxy\anaconda3\envs\forecasting\lib\site-packages\pip\_internal\cli\progress_bars.py", line 168, in iter
    for x in it:
  File "C:\Users\wxy\anaconda3\envs\forecasting\lib\site-packages\pip\_internal\network\utils.py", line 64, in response_chunks
    for chunk in response.raw.stream(
  File "C:\Users\wxy\anaconda3\envs\forecasting\lib\site-packages\pip\_vendor\urllib3\response.py", line 576, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Users\wxy\anaconda3\envs\forecasting\lib\site-packages\pip\_vendor\urllib3\response.py", line 541, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "C:\Users\wxy\anaconda3\envs\forecasting\lib\contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\wxy\anaconda3\envs\forecasting\lib\site-packages\pip\_vendor\urllib3\response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

**Comment by jdb78** [comment]
Looks like a pip issue not related to pytorch-forecasting. Suggest you give it another go.
