### ISSUE TITLE
Train without validation set

### ISSUE THREAD

**Issue by ntarouis** [jdb78/pytorch-forecasting#585]
PyTorch-Forecasting version: 0.9.0
PyTorch version: 1.9.0+cu102
Python version: 3.7.4

As mentioned in the paper "N-BEATS: NEURAL BASIS EXPANSION ANALYSIS FOR INTERPRETABLE TIME SERIES FORECASTING": 
"We split each dataset into train, validation and test subsets. The test subset is the standard test set
previously defined for each dataset (M4 Team, 2018a; Makridakis & Hibon, 2000; Athanasopoulos
et al., 2011). The validation and train subsets for each dataset are obtained by splitting their full train
sets at the boundary of the last horizon of each time series.  **We use the train and validation subsets to tune hyperparameters. Once the hyperparameters are determined, we train the model on the full train set and report results on the test set**"

However, using this library, it seems that there isn't a way to train on the full train set (after tuning hyperparameters), since there are  other hyperparameters such as gradient_clip_val, reduce_on_plateau_size that depend on the validation  loss .

How can we overcome this problem and train on the full train set without validation set?

**Comment by yuntai** [comment]
For my case, I recorded the learning rate schedule from a validation run w/ early stopping and set it to the `learning_rate` parameter as a list in `TemporalFusionTransformer.from_dataset()` and, from the code, I see `reduce_on_plateau_size` is ignored. Used other hyperparameters determined in the CV process including `max_epoch`.

**Comment by sayanb-playground** [comment]
I'm facing similar issue when trying to retrain the TFT model without a validation dataloader. The training with both train and val dataloader works fine. But when I try to train on the full data, I get the following error:

```
Traceback (most recent call last):
  File "tft_mvp_code/final_testing/main_tft_train_val_retrain.py", line 87, in <module>
    retrain_for_all_clusters(tft.train_val_dtloaders.keys())
  File "tft_mvp_code/final_testing/main_tft_train_val_retrain.py", line 57, in retrain_for_all_clusters
    train_time_taken, ckpt_path = tft_obj.fit_model(**train_kwargs)
  File "tft_mvp_code/final_testing/blob.egg/training/ts_tft/executor/tft.py", line 281, in fit_model
  File "miniconda3/envs/py37_tft/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 771, in fit
    self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
  File "miniconda3/envs/py37_tft/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 723, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "miniconda3/envs/py37_tft/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 811, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "miniconda3/envs/py37_tft/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1236, in _run
    results = self._run_stage()
  File "miniconda3/envs/py37_tft/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1323, in _run_stage
    return self._run_train()
  File "miniconda3/envs/py37_tft/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1353, in _run_train
    self.fit_loop.run()
  File "miniconda3/envs/py37_tft/lib/python3.7/site-packages/pytorch_lightning/loops/base.py", line 205, in run
    self.on_advance_end()
  File "miniconda3/envs/py37_tft/lib/python3.7/site-packages/pytorch_lightning/loops/fit_loop.py", line 303, in on_advance_end
    self.epoch_loop.update_lr_schedulers("epoch", update_plateau_schedulers=True)
  File "miniconda3/envs/py37_tft/lib/python3.7/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 435, in update_lr_schedulers
    opt_indices=[opt_idx for opt_idx, _ in active_optimizers],
  File "miniconda3/envs/py37_tft/lib/python3.7/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 478, in _update_learning_rates
    
    f"ReduceLROnPlateau conditioned on metric {monitor_key}"
pytorch_lightning.utilities.exceptions.MisconfigurationException: ReduceLROnPlateau conditioned on metric val_loss which is not available. Available metrics are: ['train_loss', 'train_loss_step', 'train_SMAPE', 'train_SMAPE_step', 'train_MAE', 'train_MAE_step', 'train_RMSE', 'train_RMSE_step', 'train_MAPE', 'train_MAPE_step', 'train_loss_epoch', 'train_SMAPE_epoch', 'train_MAE_epoch', 'train_RMSE_epoch', 'train_MAPE_epoch']. Condition can be set using `monitor` key in lr scheduler dict

```

I'm attaching the relevant section of the code, as I can't upload the full dump.
My trainer is coming via this function:
```
pl.Trainer(
                max_epochs=constants.TFT_PARAMS['max_epochs'] if not to_retrain
                else constants.TFT_PARAMS['retrain_max_epochs'],
                gpus=gpu_id,
                accelerator='ddp',
                weights_summary="top",
                gradient_clip_val=self.opt_hyperparams_dict[cluster_id]['gradient_clip_val'],
                callbacks=[lr_logger, early_stop_callback] if not to_retrain else None,
                logger=tb_logger
            )
```

The lightning module is obtained via the following:
```
TemporalFusionTransformer.from_dataset(
            train_obj,
            learning_rate=self.opt_hyperparams_dict[cluster_id]['learning_rate'],
            hidden_size=self.opt_hyperparams_dict[cluster_id]['hidden_size'],
            attention_head_size=self.opt_hyperparams_dict[cluster_id]['attention_head_size'],
            dropout=self.opt_hyperparams_dict[cluster_id]['dropout'],
            hidden_continuous_size=self.opt_hyperparams_dict[cluster_id]['hidden_continuous_size'],
            output_size=7,
            loss=QuantileLoss(),
            log_interval=5
        )
```

My env:
Python 3.7.13
pytorch-forecasting==0.9.0
pytorch-lightning==1.6.5
torch==1.11.0
torchmetrics==0.5.0
